spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ProYI/SpringConfig.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      cors:
        # 把对应的接口暴露出去
        exposed-headers: "*"